### ISSUE TITLE
tar.gz is always performed

### ISSUE THREAD

**Issue by mcaubet** [pennycoders/puppet-zookeeper#6]
if $root_dir {
    $extract_dir = "${target}/${root_dir}"
  } else {
    $extract_dir = "${target}/${name}"
  }

root_dir can not be defined. If target = installDir = /opt/zookeeper-2.4.9 then "creates" expects /opt/zookeeper-2.4.9/zookeeper, so it always keep unzipping the file everytime that puppet runs.

In order to solve this, root_dir should be able to be defined. By adding in the install.pp the option root_dir as follows it should work,

  archive { 'zookeeper':
    ensure           => present,
    url              => $url,
    src_target       => $tmpDir,
    target           => $installDir,
    root_dir         => $rootDir,
    strip_components => 1,
    follow_redirects => $follow_redirects,
    extension        => $extension,
    checksum         => $checksum,
    notify           => [File[$installDir]],
    digest_string    => $digest_string,
    digest_type      => $digest_type
  }

where rootDir should be defined as "/"

**Comment by pennycoders** [comment]
Successfully merged your fork. Marking this issue as closed
